sonar.projectKey=jbsoft_project-conqueror_lizard-ts
sonar.organization=jbsoft


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=project-conqueror_lizard-ts
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file.
sonar.language=ts,js
sonar.sources=src
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.environments=node
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/vendor/**

# Tests
sonar.tests=tests

# Disable other language sensors
sonar.java.binaries=
sonar.cfamily.cache.enabled=false
