export type AnalysisType =
  | "abs-churn"
  | "age"
  | "author-churn"
  | "authors"
  | "communication"
  | "coupling"
  | "entity-churn"
  | "entity-effort"
  | "entity-ownership"
  | "fragmentation"
  | "identity"
  | "main-dev-by-revs"
  | "main-dev"
  | "refactoring-main-dev"
  | "revisions"
  | "soc"
  | "summary";
