import {
  Chart,
  BarController,
  BarElement,
  BubbleController,
  LineController,
  LineElement,
  PointElement,
  DoughnutController,
  PieController,
  ArcElement,
  Filler,
  CategoryScale,
  LinearScale,
  TimeScale,
  Tooltip,
  Legend,
  Title,
} from "chart.js";
import { TreemapController, TreemapElement } from "chartjs-chart-treemap";

Chart.register(
  BarController,
  BarElement,
  BubbleController,
  LineController,
  LineElement,
  PointElement,
  DoughnutController,
  PieController,
  ArcElement,
  Filler,
  CategoryScale,
  LinearScale,
  TimeScale,
  Tooltip,
  Legend,
  Title,
  TreemapController,
  TreemapElement,
);
